In [1]:
!pip3 install numpy

## We are going to learn numpy now!

### this is a new headline

In [3]:
import numpy as np

In [13]:
arr=np.array([[1,2,3],
             [4,5,6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [10]:
arr.shape

(3,)

In [14]:
arr.size

6

In [12]:
arr.dtype

dtype('int64')

In [16]:
a=np.array([[1,2,3],
             [4,5,6]],dtype='float')

In [17]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
b=np.array((1,2,3))

In [19]:
b

array([1, 2, 3])

In [67]:
c=np.zeros((4,4))

In [21]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.arange?

In [25]:
np.eye?

In [28]:
f=np.arange(0,30,5)
print(f)
g=np.linspace(0,30,10)
print(g)

[ 0  5 10 15 20 25]
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]


In [35]:
 arr=np.array([[1,2,3,4],
             [5,2,4,2],
               [1,2,0,1]])
newarr=arr.reshape((4,3))
newarr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [36]:
np.random.random()

0.6219204963334538

In [39]:
arr=newarr.flatten()

In [40]:
arr

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

In [47]:
arr=np.array([[-1,-2,-3,-4],
    [-5,-6,-7,-8],
    [9,10,12,13],
    [3,2,45,54]])
arr

array([[-1, -2, -3, -4],
       [-5, -6, -7, -8],
       [ 9, 10, 12, 13],
       [ 3,  2, 45, 54]])

In [42]:
arr[1:,:3]

array([[ 5,  6,  7],
       [ 9, 10, 12],
       [ 3,  2, 45]])

In [43]:
arr[1::2,:3:2]

array([[ 5,  7],
       [ 3, 45]])

In [49]:
#conditional indexinig
cond=arr>0 # cond is a boolean array
arr[cond]

array([ 9, 10, 12, 13,  3,  2, 45, 54])

In [50]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [51]:
a*3

array([ 3,  6,  9, 12])

In [52]:
arr.T

array([[-1, -5,  9,  3],
       [-2, -6, 10,  2],
       [-3, -7, 12, 45],
       [-4, -8, 13, 54]])

In [53]:
arr.max()

54

In [60]:
arr.max(axis=1) # row-wise maximum element

array([-1, -5, 13, 54])

In [61]:
arr.max(axis=0) # column wise maximum element

array([ 9, 10, 45, 54])

In [62]:
arr.sum()

112

In [65]:
arr.cumsum(axis=1)

array([[ -1,  -3,  -6, -10],
       [ -5, -11, -18, -26],
       [  9,  19,  31,  44],
       [  3,   5,  50, 104]])

In [68]:
arr+c # add arrays

array([[-1., -2., -3., -4.],
       [-5., -6., -7., -8.],
       [ 9., 10., 12., 13.],
       [ 3.,  2., 45., 54.]])

In [69]:
arr*c # multiply arrays (elementwise multiplication)

array([[-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [70]:
arr.dot(c) # matrix multiplication

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.sin(arr)

array([[-0.84147098, -0.90929743, -0.14112001,  0.7568025 ],
       [ 0.95892427,  0.2794155 , -0.6569866 , -0.98935825],
       [ 0.41211849, -0.54402111, -0.53657292,  0.42016704],
       [ 0.14112001,  0.90929743,  0.85090352, -0.55878905]])

In [72]:
np.exp(arr)

array([[3.67879441e-01, 1.35335283e-01, 4.97870684e-02, 1.83156389e-02],
       [6.73794700e-03, 2.47875218e-03, 9.11881966e-04, 3.35462628e-04],
       [8.10308393e+03, 2.20264658e+04, 1.62754791e+05, 4.42413392e+05],
       [2.00855369e+01, 7.38905610e+00, 3.49342711e+19, 2.83075330e+23]])

In [73]:
np.sqrt(arr)

<ipython-input-73-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [3.        , 3.16227766, 3.46410162, 3.60555128],
       [1.73205081, 1.41421356, 6.70820393, 7.34846923]])

In [74]:
np.sort(arr,axis=None)

array([-8, -7, -6, -5, -4, -3, -2, -1,  2,  3,  9, 10, 12, 13, 45, 54])

In [75]:
np.sort(arr,axis=1)

array([[-4, -3, -2, -1],
       [-8, -7, -6, -5],
       [ 9, 10, 12, 13],
       [ 2,  3, 45, 54]])

In [78]:
np.sort(arr,axis=0,kind='mergesort')

array([[-5, -6, -7, -8],
       [-1, -2, -3, -4],
       [ 3,  2, 12, 13],
       [ 9, 10, 45, 54]])

# Stacking and Splitting

In [81]:
a=np.array([[1,2],
          [3,4]])
b=np.array([[5,6],
           [7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [86]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
c=[5,6]
np.column_stack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

In [90]:
np.concatenate((a,b),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [93]:
a=np.array([[1,2,3,4,5,6],
           [7,8,9,1,2,3]])
np.hsplit(a,2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [1, 2, 3]])]

In [94]:
np.vsplit(a,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[7, 8, 9, 1, 2, 3]])]